/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CommandItem: typeof import('./components/command/CommandItem.vue')['default']
    CommandKey: typeof import('./components/command/CommandKey.vue')['default']
    CommandPanel: typeof import('./components/command/CommandPanel.vue')['default']
    Counter: typeof import('./components/Counter.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    ModalContainer: typeof import('./components/modal/ModalContainer.vue')['default']
    ModalDialog: typeof import('./components/modal/ModalDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsBuildInfo: typeof import('./components/settings/SettingsBuildInfo.vue')['default']
    SettingsScreenFull: typeof import('./components/settings/SettingsScreenFull.vue')['default']
    SettingsThemeColors: typeof import('./components/settings/SettingsThemeColors.vue')['default']
    TheNav: typeof import('./components/nav/TheNav.vue')['default']
  }
}
