/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Counter: typeof import('./components/Counter.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsBuildInfo: typeof import('./components/settings/SettingsBuildInfo.vue')['default']
    SettingsScreenFull: typeof import('./components/settings/SettingsScreenFull.vue')['default']
    SettingsThemeColors: typeof import('./components/settings/SettingsThemeColors.vue')['default']
    TheNav: typeof import('./components/nav/TheNav.vue')['default']
  }
}
